Update dbt_pipeline.yml

diff --git a/.github/workflows/dbt_pipeline.yml b/.github/workflows/dbt_pipeline.yml
--- a/.github/workflows/dbt_pipeline.yml
+++ b/.github/workflows/dbt_pipeline.yml
@@ -109,6 +109,7 @@ jobs:
           cp target/index.html public/ || echo "index.html missing"
           cp target/manifest.json public/ || echo "manifest.json missing"
           cp target/catalog.json public/ || echo "catalog.json missing"
+          cp target/run_results.json public/ || echo "run_results.json missing"
 
           if [ -d "target/assets" ]; then
             cp -r target/assets public/assets
